book:
  repo-url: "https://github.com/dilob-mhb/praxis-it"
  issue-url: "https://github.com/dilob-mhb/praxis-it/issues"
  google-analytics: 
    tracking-id: "G-W0VVGPQSBH"

format:
  html:
    comments:
      giscus: 
        repo: dilob-mhb/praxis-it
